### ISSUE TITLE
Getting error on database does not exist (crawl-config db)

### ISSUE THREAD

**Issue by markstur** [IBM/voice-of-the-customer#6]
README doesn't say to create it (and why not auto-create anyway) but I get this error:

*** Checking Access is Configured...
*** All Good, Keep Going...
Web server listening at: http://localhost:3000
Browse your REST API at http://localhost:3000/explorer
Connection fails: Error: Database does not exist.
It will be retried for the next request.
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Database does not exist.

It turns out that the voc-content DB was created, but the CLOUDANT_CRAWL_CONFIG_DB_NAME was not created.

**Comment by wernervz** [comment]
The database in question is referenced in 2 places.  The first is in the env-vars.json file.  The second is in the server/config/cloudant-config.json file.  The second file is used when the app starts up to validate that the database is there and all indexes etc are created.  The database name in both these files must be the same.
